definitions:
  model.TestData:
    properties:
      count:
        type: integer
      name:
        type: string
    type: object
info:
  contact: {}
paths:
  /test:
    get:
      description: 用来测试的接口
      parameters:
      - description: id
        in: formData
        name: id
        required: true
        type: integer
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 测试接口
      tags:
      - Demo
  /test1:
    post:
      description: 用来测试的接口1
      parameters:
      - description: 你的名字
        in: formData
        name: name
        required: true
        type: string
      - description: 用户Token
        in: header
        name: usertoken
        type: string
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/model.TestData'
      summary: 测试接口1
      tags:
      - Demo
  /user/login:
    post:
      description: 用户登录接口
      parameters:
      - description: 手机号
        in: formData
        name: usertel
        required: true
        type: string
      responses:
        "200":
          description: OK
          schema:
            type: string
      summary: 用户登录接口
      tags:
      - user 用户管理
swagger: "2.0"
